[phases.setup]
nixPkgs = ['php83', 'php83Extensions.mysqli', 'php83Extensions.pdo', 'php83Extensions.pdo_mysql', 'php83Extensions.mbstring']

[phases.build]
cmds = ['chmod +x start.sh']

[start]
cmd = './start.sh'
