[phases.setup]
nixPkgs = ['php84', 'php84Extensions.mysqli', 'php84Extensions.pdo', 'php84Extensions.pdo_mysql', 'php84Extensions.mbstring']

[phases.build]
cmds = ['chmod +x start.sh']

[start]
cmd = './start.sh'
